/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package creditobancario.views;

import creditobancario.controllers.MotorController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import jess.JessException;
import java.net.URL;
import java.net.URLEncoder;
import org.openide.awt.HtmlBrowser.URLDisplayer;


/**
 *
 * @author Kattya Desiderio
 */
public class AplicationForm extends javax.swing.JFrame {

    private MotorController motorController;
    String edad;
    JFrame preform;
    
    public AplicationForm() {
        initComponents();
        this.setVisible(true);
        
//        PreForm.jTextField2.setText("valor2");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_CI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_edad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        txt_pagoLuz = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_femenino = new javax.swing.JRadioButton();
        btn_masculino = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        btn_soltero = new javax.swing.JRadioButton();
        btn_casado = new javax.swing.JRadioButton();
        btn_divorciado = new javax.swing.JRadioButton();
        btn_viudo = new javax.swing.JRadioButton();
        op_seguro = new javax.swing.JCheckBox();
        op_vehiculo = new javax.swing.JCheckBox();
        op_casa = new javax.swing.JCheckBox();
        op_departamento = new javax.swing.JCheckBox();
        op_ctaCorriente = new javax.swing.JCheckBox();
        op_ctaAhorro = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_enviar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_pagoAgua = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_pagoTelf = new javax.swing.JTextField();
        op_hipoteca = new javax.swing.JCheckBox();
        op_credDirecto = new javax.swing.JCheckBox();
        op_tarjetasCred = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        txt_credHipoteca = new javax.swing.JTextField();
        txt_pagoTarjetas = new javax.swing.JTextField();
        txt_creditoCasaComercial = new javax.swing.JTextField();
        btn_check = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(743, 743));
        setMinimumSize(new java.awt.Dimension(743, 743));
        setPreferredSize(new java.awt.Dimension(743, 743));
        setSize(new java.awt.Dimension(743, 743));
        getContentPane().setLayout(null);
        getContentPane().add(txt_CI);
        txt_CI.setBounds(140, 110, 136, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("CI / RUC:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 110, 70, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Name:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 140, 40, 17);
        getContentPane().add(txt_nombre);
        txt_nombre.setBounds(140, 140, 227, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Surname:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 170, 60, 17);
        getContentPane().add(txt_apellido);
        txt_apellido.setBounds(140, 170, 228, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Age:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 200, 40, 17);

        txt_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_edadActionPerformed(evt);
            }
        });
        getContentPane().add(txt_edad);
        txt_edad.setBounds(140, 200, 50, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Location:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 230, 57, 17);

        txt_direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_direccion.setAutoscrolls(false);
        txt_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direccionActionPerformed(evt);
            }
        });
        getContentPane().add(txt_direccion);
        txt_direccion.setBounds(140, 230, 222, 20);

        txt_pagoLuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pagoLuzActionPerformed(evt);
            }
        });
        getContentPane().add(txt_pagoLuz);
        txt_pagoLuz.setBounds(140, 360, 100, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel9.setText("Credit Application Form");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(181, 26, 495, 58);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Sex:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(520, 100, 40, 20);

        btn_femenino.setText("Female");
        btn_femenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_femeninoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_femenino);
        btn_femenino.setBounds(560, 103, 90, 20);

        btn_masculino.setText("Male");
        getContentPane().add(btn_masculino);
        btn_masculino.setBounds(560, 123, 93, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Marital status:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(450, 150, 110, 17);

        btn_soltero.setText("Single");
        btn_soltero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_solteroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_soltero);
        btn_soltero.setBounds(560, 153, 70, 20);

        btn_casado.setText("Married");
        getContentPane().add(btn_casado);
        btn_casado.setBounds(560, 173, 93, 20);

        btn_divorciado.setText("Divorced");
        btn_divorciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divorciadoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_divorciado);
        btn_divorciado.setBounds(560, 193, 80, 20);

        btn_viudo.setText("Widow");
        btn_viudo.setToolTipText("");
        getContentPane().add(btn_viudo);
        btn_viudo.setBounds(560, 213, 93, 20);

        op_seguro.setText("Owns a life insurance");
        op_seguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_seguroActionPerformed(evt);
            }
        });
        getContentPane().add(op_seguro);
        op_seguro.setBounds(230, 300, 150, 23);

        op_vehiculo.setText("Vehicle");
        op_vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_vehiculoActionPerformed(evt);
            }
        });
        getContentPane().add(op_vehiculo);
        op_vehiculo.setBounds(140, 260, 80, 23);

        op_casa.setText("House");
        op_casa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_casaActionPerformed(evt);
            }
        });
        getContentPane().add(op_casa);
        op_casa.setBounds(140, 280, 80, 23);

        op_departamento.setText("Department");
        op_departamento.setToolTipText("");
        op_departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_departamentoActionPerformed(evt);
            }
        });
        getContentPane().add(op_departamento);
        op_departamento.setBounds(140, 300, 90, 23);

        op_ctaCorriente.setText("Active checking account");
        op_ctaCorriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_ctaCorrienteActionPerformed(evt);
            }
        });
        getContentPane().add(op_ctaCorriente);
        op_ctaCorriente.setBounds(230, 260, 160, 23);

        op_ctaAhorro.setText("Active savings account");
        op_ctaAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_ctaAhorroActionPerformed(evt);
            }
        });
        getContentPane().add(op_ctaAhorro);
        op_ctaAhorro.setBounds(230, 280, 160, 23);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Payment amounts per month");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(40, 330, 210, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Electric light:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 360, 90, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Water:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(70, 390, 50, 17);

        btn_enviar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_enviar.setText("Send");
        btn_enviar.setToolTipText("");
        btn_enviar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_enviar.setName("btn_enviar"); // NOI18N
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_enviar);
        btn_enviar.setBounds(310, 590, 90, 27);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Assets:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(70, 260, 43, 17);

        txt_pagoAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pagoAguaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_pagoAgua);
        txt_pagoAgua.setBounds(140, 390, 100, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Debts acquired:");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(20, 460, 110, 17);

        txt_pagoTelf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pagoTelfActionPerformed(evt);
            }
        });
        getContentPane().add(txt_pagoTelf);
        txt_pagoTelf.setBounds(140, 420, 100, 20);

        op_hipoteca.setText("Mortage credit");
        op_hipoteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_hipotecaActionPerformed(evt);
            }
        });
        getContentPane().add(op_hipoteca);
        op_hipoteca.setBounds(140, 460, 100, 23);

        op_credDirecto.setText("Comercial direct credit");
        op_credDirecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_credDirectoActionPerformed(evt);
            }
        });
        getContentPane().add(op_credDirecto);
        op_credDirecto.setBounds(140, 490, 140, 23);

        op_tarjetasCred.setText("Credit cards");
        op_tarjetasCred.setToolTipText("");
        op_tarjetasCred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_tarjetasCredActionPerformed(evt);
            }
        });
        getContentPane().add(op_tarjetasCred);
        op_tarjetasCred.setBounds(140, 520, 90, 23);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Phone:");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(70, 420, 60, 17);

        txt_credHipoteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_credHipotecaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_credHipoteca);
        txt_credHipoteca.setBounds(290, 460, 120, 20);

        txt_pagoTarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pagoTarjetasActionPerformed(evt);
            }
        });
        getContentPane().add(txt_pagoTarjetas);
        txt_pagoTarjetas.setBounds(290, 520, 120, 20);

        txt_creditoCasaComercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_creditoCasaComercialActionPerformed(evt);
            }
        });
        getContentPane().add(txt_creditoCasaComercial);
        txt_creditoCasaComercial.setBounds(290, 490, 120, 20);

        btn_check.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_check.setText("Check");
        btn_check.setToolTipText("Validate the information within the credit bureau");
        btn_check.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkActionPerformed(evt);
            }
        });
        getContentPane().add(btn_check);
        btn_check.setBounds(190, 590, 90, 31);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_edadActionPerformed

    private void txt_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccionActionPerformed

    private void txt_pagoLuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pagoLuzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pagoLuzActionPerformed

    private void btn_femeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_femeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_femeninoActionPerformed

    private void btn_solteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_solteroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_solteroActionPerformed

    private void btn_divorciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divorciadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_divorciadoActionPerformed

    private void op_seguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_seguroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_seguroActionPerformed

    private void op_vehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_vehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_vehiculoActionPerformed

    private void op_casaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_casaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_casaActionPerformed

    private void op_departamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_departamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_departamentoActionPerformed

    private void op_ctaCorrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_ctaCorrienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_ctaCorrienteActionPerformed

    private void op_ctaAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_ctaAhorroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_ctaAhorroActionPerformed

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
        edad = txt_edad.getText();
//        System.out.println(edad);
        
        try {
            this.validarEdad(edad);
        } catch (JessException ex) {
            Logger.getLogger(AplicationForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_enviarActionPerformed

    private void txt_pagoAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pagoAguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pagoAguaActionPerformed

    private void txt_pagoTelfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pagoTelfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pagoTelfActionPerformed

    private void op_hipotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_hipotecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_hipotecaActionPerformed

    private void op_credDirectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_credDirectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_credDirectoActionPerformed

    private void op_tarjetasCredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_tarjetasCredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_tarjetasCredActionPerformed

    private void txt_credHipotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_credHipotecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_credHipotecaActionPerformed

    private void txt_pagoTarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pagoTarjetasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pagoTarjetasActionPerformed

    private void txt_creditoCasaComercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_creditoCasaComercialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_creditoCasaComercialActionPerformed

    private void btn_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkActionPerformed
        try {
            URLDisplayer.getDefault().showURL(new URL("https://www.equifax.com.ec/decida/login.aspx"));
        } catch (Exception eee) {
            return;
        }
    }//GEN-LAST:event_btn_checkActionPerformed
     
    public void validarEdad(String edad) throws JessException{
        int edadobj = Integer.parseInt(edad);
        
        if (edadobj < 18 ||  edadobj >=65)
        {
            System.out.println("es menor");
            this.motorController.afirmar("(respuesta si)");
        }
        else{
            System.out.println("es mayor");
            this.motorController.afirmar("(respuesta no)");
        }
            
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplicationForm().setVisible(true);
            }
        });
    }
    
    public void setMotorController(MotorController motorController){
        this.motorController = motorController;
    }
    
    
    
    public void getPreguntas(String pregunta) throws JessException{
    
     if(pregunta.equals("¿Vericado ingresos?")){
            //String ingreso = txt_ingreso.getText();
           // if(ingreso.equals("")){
                this.motorController.afirmar("(respuesta no)");
            //}
            //else{
              //  this.motorController.afirmar("(respuesta si)");
            //}
     }
    }
    
    public void cambiarPregunta(String pregunta) throws JessException{
        
        System.out.println("entre a cambiar pregunta");
        System.out.println(pregunta);
        this.getPreguntas(pregunta);
//        jlPregunta.setText(pregunta);
//        jrbNo.setVisible(true);
//        jrbSi.setVisible(true);
//        jbSiguiente.setText("Siguiente");
    }
    
    public void darRespuesta(String respuesta){
         System.out.println("entre a respuesta");
//        jlPregunta.setText(respuesta);
//        jrbNo.setVisible(false);
//        jrbSi.setVisible(false);
//        jbSiguiente.setText("Otra vez");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btn_casado;
    private javax.swing.JButton btn_check;
    private javax.swing.JRadioButton btn_divorciado;
    private javax.swing.JButton btn_enviar;
    private javax.swing.JRadioButton btn_femenino;
    private javax.swing.JRadioButton btn_masculino;
    private javax.swing.JRadioButton btn_soltero;
    private javax.swing.JRadioButton btn_viudo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox op_casa;
    private javax.swing.JCheckBox op_credDirecto;
    private javax.swing.JCheckBox op_ctaAhorro;
    private javax.swing.JCheckBox op_ctaCorriente;
    private javax.swing.JCheckBox op_departamento;
    private javax.swing.JCheckBox op_hipoteca;
    private javax.swing.JCheckBox op_seguro;
    private javax.swing.JCheckBox op_tarjetasCred;
    private javax.swing.JCheckBox op_vehiculo;
    private javax.swing.JTextField txt_CI;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_credHipoteca;
    private javax.swing.JTextField txt_creditoCasaComercial;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_pagoAgua;
    private javax.swing.JTextField txt_pagoLuz;
    private javax.swing.JTextField txt_pagoTarjetas;
    private javax.swing.JTextField txt_pagoTelf;
    // End of variables declaration//GEN-END:variables
}
