/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package creditobancario.views;

import creditobancario.controllers.MotorController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import jess.JessException;
import java.net.URL;
import java.net.URLEncoder;
import org.openide.awt.HtmlBrowser.URLDisplayer;


/**
 *
 * @author Kattya Desiderio
 */
public class AplicationForm extends javax.swing.JFrame {

    private MotorController motorController;
    String edad;
    JFrame preform;
    
    public AplicationForm() {
        initComponents();
        this.setVisible(true);
        
//        PreForm.jTextField2.setText("valor2");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_CI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_edad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_femenino = new javax.swing.JRadioButton();
        btn_masculino = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        btn_soltero = new javax.swing.JRadioButton();
        btn_casado = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        btn_enviar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        poseeTarjetaCredito = new javax.swing.JCheckBox();
        montoAlto = new javax.swing.JCheckBox();
        montoBajo = new javax.swing.JCheckBox();
        btn_check = new javax.swing.JButton();
        plazoBajo = new javax.swing.JCheckBox();
        frecuenciaUsoTC = new javax.swing.JCheckBox();
        tuvoCreditos = new javax.swing.JCheckBox();
        pagaATiempo = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        plazoAlto = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(743, 743));
        setMinimumSize(new java.awt.Dimension(743, 743));
        setPreferredSize(new java.awt.Dimension(743, 743));
        setSize(new java.awt.Dimension(743, 743));
        getContentPane().setLayout(null);
        getContentPane().add(txt_CI);
        txt_CI.setBounds(140, 110, 136, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("CI / RUC:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 110, 70, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("If the answer is NO leave the square in blank");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 300, 290, 17);
        getContentPane().add(txt_nombre);
        txt_nombre.setBounds(140, 140, 227, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Surname:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 170, 60, 17);
        getContentPane().add(txt_apellido);
        txt_apellido.setBounds(140, 170, 228, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Age:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 200, 40, 17);

        txt_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_edadActionPerformed(evt);
            }
        });
        getContentPane().add(txt_edad);
        txt_edad.setBounds(140, 200, 50, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Location:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 230, 57, 17);

        txt_direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_direccion.setAutoscrolls(false);
        txt_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direccionActionPerformed(evt);
            }
        });
        getContentPane().add(txt_direccion);
        txt_direccion.setBounds(140, 230, 222, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel9.setText("Credit Application Form");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(181, 26, 495, 58);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Sex:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(520, 100, 40, 20);

        btn_femenino.setText("Female");
        btn_femenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_femeninoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_femenino);
        btn_femenino.setBounds(560, 103, 90, 20);

        btn_masculino.setText("Male");
        getContentPane().add(btn_masculino);
        btn_masculino.setBounds(560, 123, 93, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Marital status:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(450, 150, 110, 17);

        btn_soltero.setText("Single");
        btn_soltero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_solteroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_soltero);
        btn_soltero.setBounds(560, 153, 70, 20);

        btn_casado.setText("Married");
        getContentPane().add(btn_casado);
        btn_casado.setBounds(560, 173, 93, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText(" Credit references");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(40, 270, 210, 17);

        btn_enviar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_enviar.setText("Send");
        btn_enviar.setToolTipText("");
        btn_enviar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_enviar.setName("btn_enviar"); // NOI18N
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_enviar);
        btn_enviar.setBounds(530, 440, 90, 27);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(30, 310, 110, 0);

        poseeTarjetaCredito.setText("Has credit cards?");
        getContentPane().add(poseeTarjetaCredito);
        poseeTarjetaCredito.setBounds(100, 500, 200, 23);

        montoAlto.setText("amount equals or greater than 31 000");
        montoAlto.setToolTipText("");
        montoAlto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montoAltoActionPerformed(evt);
            }
        });
        getContentPane().add(montoAlto);
        montoAlto.setBounds(130, 380, 230, 23);

        montoBajo.setText("amount equals or less than 30 000");
        montoBajo.setToolTipText("");
        montoBajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montoBajoActionPerformed(evt);
            }
        });
        getContentPane().add(montoBajo);
        montoBajo.setBounds(130, 360, 210, 23);

        btn_check.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_check.setText("Check");
        btn_check.setToolTipText("Validate the information within the credit bureau");
        btn_check.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkActionPerformed(evt);
            }
        });
        getContentPane().add(btn_check);
        btn_check.setBounds(530, 480, 90, 31);

        plazoBajo.setText("credit term equals or less than 10 years");
        plazoBajo.setToolTipText("");
        plazoBajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plazoBajoActionPerformed(evt);
            }
        });
        getContentPane().add(plazoBajo);
        plazoBajo.setBounds(130, 410, 230, 23);

        frecuenciaUsoTC.setText("Uses them often?");
        frecuenciaUsoTC.setToolTipText("");
        frecuenciaUsoTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frecuenciaUsoTCActionPerformed(evt);
            }
        });
        getContentPane().add(frecuenciaUsoTC);
        frecuenciaUsoTC.setBounds(140, 530, 170, 23);

        tuvoCreditos.setText("had a previous bank loan?");
        getContentPane().add(tuvoCreditos);
        tuvoCreditos.setBounds(100, 330, 170, 23);

        pagaATiempo.setText("Make payments before deadline");
        getContentPane().add(pagaATiempo);
        pagaATiempo.setBounds(100, 470, 200, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Name:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 140, 40, 17);

        plazoAlto.setText("credit term equals or greater than 11 years");
        plazoAlto.setToolTipText("");
        plazoAlto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plazoAltoActionPerformed(evt);
            }
        });
        getContentPane().add(plazoAlto);
        plazoAlto.setBounds(130, 430, 270, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_edadActionPerformed

    private void txt_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccionActionPerformed

    private void btn_femeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_femeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_femeninoActionPerformed

    private void btn_solteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_solteroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_solteroActionPerformed

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
        edad = txt_edad.getText();
//        System.out.println(edad);
        
        try {
            this.validarEdad(edad);
        } catch (JessException ex) {
            Logger.getLogger(AplicationForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_enviarActionPerformed

    private void montoAltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoAltoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montoAltoActionPerformed

    private void montoBajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoBajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montoBajoActionPerformed

    private void btn_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkActionPerformed
        try {
            URLDisplayer.getDefault().showURL(new URL("https://www.equifax.com.ec/decida/login.aspx"));
        } catch (Exception eee) {
            return;
        }
    }//GEN-LAST:event_btn_checkActionPerformed

    private void plazoBajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plazoBajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plazoBajoActionPerformed

    private void frecuenciaUsoTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frecuenciaUsoTCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frecuenciaUsoTCActionPerformed

    private void plazoAltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plazoAltoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plazoAltoActionPerformed
     
    public void validarEdad(String edad) throws JessException{
        int edadobj = Integer.parseInt(edad);
        
        if (edadobj < 18 ||  edadobj >=65)
        {
            System.out.println("es menor");
            this.motorController.afirmar("(respuesta si)");
        }
        else{
            System.out.println("es mayor");
            this.motorController.afirmar("(respuesta no)");
        }
            
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplicationForm().setVisible(true);
            }
        });
    }
    
    public void setMotorController(MotorController motorController){
        this.motorController = motorController;
    }
    
    
    
    public void getPreguntas(String pregunta) throws JessException{
    
     if(pregunta.equals("¿Vericado ingresos?")){
            //String ingreso = txt_ingreso.getText();
           // if(ingreso.equals("")){
                this.motorController.afirmar("(respuesta no)");
            //}
            //else{
              //  this.motorController.afirmar("(respuesta si)");
            //}
     }
    }
    
    public void cambiarPregunta(String pregunta) throws JessException{
        
        System.out.println("entre a cambiar pregunta");
        System.out.println(pregunta);
        this.getPreguntas(pregunta);
//        jlPregunta.setText(pregunta);
//        jrbNo.setVisible(true);
//        jrbSi.setVisible(true);
//        jbSiguiente.setText("Siguiente");
    }
    
    public void darRespuesta(String respuesta){
         System.out.println("entre a respuesta");
//        jlPregunta.setText(respuesta);
//        jrbNo.setVisible(false);
//        jrbSi.setVisible(false);
//        jbSiguiente.setText("Otra vez");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btn_casado;
    private javax.swing.JButton btn_check;
    private javax.swing.JButton btn_enviar;
    private javax.swing.JRadioButton btn_femenino;
    private javax.swing.JRadioButton btn_masculino;
    private javax.swing.JRadioButton btn_soltero;
    private javax.swing.JCheckBox frecuenciaUsoTC;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox montoAlto;
    private javax.swing.JCheckBox montoBajo;
    private javax.swing.JCheckBox pagaATiempo;
    private javax.swing.JCheckBox plazoAlto;
    private javax.swing.JCheckBox plazoBajo;
    private javax.swing.JCheckBox poseeTarjetaCredito;
    private javax.swing.JCheckBox tuvoCreditos;
    private javax.swing.JTextField txt_CI;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
